server:
  port: 8206
spring:
  application:
    name: cart-server
  redis:
    host: 192.168.2.179
    password: java2001
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my-shop-v3?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

# 指明mapper映射文件的位置
mybatis:
  mapper-locations: classpath:mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9201/eureka/


