dubbo:
  application:
    name: view-facade
  registry:
    address: zookeeper://172.16.253.35:2181
  protocol:
    port: 20887
server:
  port: 9084
spring:
#  redis:
#    host: 172.16.253.7
#    port: 6379
#    password: java2007
#    jedis:
#      pool:
#        max-active: 8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_my_device?serverTimezone=Asia/Shanghai
    username: root
    password: qf123456
    type: com.alibaba.druid.pool.DruidDataSource

# 指明mapper映射文件的位置
mybatis:
  mapper-locations: classpath:META-INF/mapper/*.xml


