server:
  port: 8090
spring:
  redis:
    host: 172.16.253.34
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 4
    password: qfjava
    port: 6379
#    cluster:
#      nodes: 172.16.253.34:7001,172.16.253.34:7002,172.16.253.34:7003

