spring:
  application:
    name: worker-provider
server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewallIntervalInSeconds: 60
