spring:
  application:
    name: worker-consumer
server:
  port: 8763

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# 配置ribbon的超时时间
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
# 配置hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
