dubbo:
  application:
    name: view-facade
  registry:
    address: zookeeper://172.16.253.6:2181
  protocol:
    port: 20881
server:
  port: 9091
spring:
  redis:
    host: 172.16.253.7
    port: 6379
    password: java2007
    jedis:
      pool:
        max-active: 8
