server:
  port: 9203
spring:
  application:
    name: sms-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9201/eureka/

aliyun:
  sms:
    accessKeyId: LTAI4G5k2QZtPMpXG88KnaEJ
    accessSecret: cKonv1CLgky0VSTCDEnc7U4YWm1KCF
    domain: dysmsapi.aliyuncs.com
    version: 2017-05-25
    signName: ABC商城
    templateCode: SMS_202810032
